apiVersion: apps/v1
kind: Deployment
metadata:
  name: formula-app-deployment
  annotations:
    kubernetes.io/change-couse: "Initional deployment of the app"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: formula-app
  template:
    metadata:
      name: myformulak8s
      labels:
        evn: prod
        app: formula-app
        app.kubernetes.io/name: formula-app
    spec:
      containers:
        - name: formulaapp
          image: gajdaltd/formulaapp:v1
          ports:
            - containerPort: 5080
              name: http-web-api
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5080

---
apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
spec:
  selector:
    app.kubernetes.io/name: formula-app
  ports:
    - name: formula-app-port
      protocol: TCP
      port: 8080
      targetPort: 5080
  type: LoadBalancer
