version: "3.9"
x-docker-data: &docker-build
  build:
    context: .
    dockerfile: Dockerfile
networks:
  formula-network:
    driver: bridge
services:
  formula-webapi:
    image: gajdaltd/formulaapp:v3
    container_name: formulaapp
    <<: *docker-build
    env_file: .env
    environment:
      SEQ__SERVERURL: "http://host.docker.internal:5341"
      SEQ__APIKEY: "${SEQ__APIKEY:-l1GosUsS8uqaxo9D3naB}"
    networks:
      - formula-network
    ports:
      - "127.0.0.1:5080:5080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: /usr/bin/curl --fail http://localhost:5080/healthz || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s